// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hrI8pwhqFumrskVwL5n49tXrOsfoJ2Y',
    appId: '1:922910858463:web:6669f3affa60aae101dd6a',
    messagingSenderId: '922910858463',
    projectId: 'project1fire-9e5f8',
    authDomain: 'project1fire-9e5f8.firebaseapp.com',
    storageBucket: 'project1fire-9e5f8.firebasestorage.app',
    measurementId: 'G-HSQS5SK31N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7wHgqqTC_Fh5bgDKuL3x5CcNlUztIqY',
    appId: '1:922910858463:android:1c9e8553ca19a6f601dd6a',
    messagingSenderId: '922910858463',
    projectId: 'project1fire-9e5f8',
    storageBucket: 'project1fire-9e5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZ3NeRa4QFwqT7fw_rhOq7sPEYgO5ICk',
    appId: '1:922910858463:ios:9668723229342f1701dd6a',
    messagingSenderId: '922910858463',
    projectId: 'project1fire-9e5f8',
    storageBucket: 'project1fire-9e5f8.firebasestorage.app',
    iosBundleId: 'com.example.firebasetesting',
  );
}
